# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: sync_from_douban

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env: 
  USER_AGENT: ${{ secrets.USER_AGENT }}
  USER_COOKIE: ${{ secrets.USER_COOKIE }}
  DOUBAN_USER_ID: ${{ secrets.DOUBAN_USER_ID }}
  DOUBAN_DAY: ${{ secrets.DOUBAN_DAY }}
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
  NOTION_BOOKS_DB: ${{ secrets.NOTION_BOOKS_DB }}
  NOTION_MUSIC_DB: ${{ secrets.NOTION_MUSIC_DB }}
  NOTION_MOVIE_DB: ${{ secrets.NOTION_MOVIE_DB }}
  NOTION_GAME_DB: ${{ secrets.NOTION_GAME_DB }}
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sync_from_douban/requirements.txt
        
    - name: generate config
      run:
        python run.py -f config
      working-directory:
        ./sync_from_douban

    - name: sync_data
      run:
        python run.py -m book -s all
      working-directory:
        ./sync_from_douban
